-- MySQL Script generated by MySQL Workbench
-- Wed May 29 15:52:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Buses
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Buses` ;

-- -----------------------------------------------------
-- Schema Buses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Buses` DEFAULT CHARACTER SET utf8 ;
USE `Buses` ;

-- -----------------------------------------------------
-- Table `Buses`.`Routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buses`.`Routes` ;

CREATE TABLE IF NOT EXISTS `Buses`.`Routes` (
  `idRoutes` VARCHAR(10) NOT NULL,
  `Drivers` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRoutes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buses`.`Stops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buses`.`Stops` ;

CREATE TABLE IF NOT EXISTS `Buses`.`Stops` (
  `idStops` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStops`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buses`.`Distances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buses`.`Distances` ;

CREATE TABLE IF NOT EXISTS `Buses`.`Distances` (
  `idDistances` INT NOT NULL,
  PRIMARY KEY (`idDistances`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buses`.`Drivers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buses`.`Drivers` ;

CREATE TABLE IF NOT EXISTS `Buses`.`Drivers` (
  `idDrivers` INT NOT NULL,
  `Last_name` VARCHAR(45) NOT NULL,
  `First_name` VARCHAR(45) NOT NULL,
  `Second_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDrivers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buses`.`Sensor_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buses`.`Sensor_data` ;

CREATE TABLE IF NOT EXISTS `Buses`.`Sensor_data` (
  `idSensor_data` INT NOT NULL,
  `Route` VARCHAR(10) NOT NULL,
  `Stop` INT NOT NULL,
  `Driver` INT NOT NULL,
  `Time_arrival` DATETIME NOT NULL,
  `Time_departure` DATETIME NOT NULL,
  PRIMARY KEY (`idSensor_data`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
